repos:
  # GDScript Toolkit
  - repo: https://github.com/Scony/godot-gdscript-toolkit
    rev: 4.3.4
    hooks:
      - id: gdlint
        name: gdlint
        description: "gdlint - linter for GDScript"
        entry: gdlint
        language: python
        language_version: python3
        require_serial: true
        types: [gdscript]
        additional_dependencies: [setuptools]
      - id: gdformat
        name: gdformat
        description: "gdformat - formatter for GDScript"
        entry: gdformat
        language: python
        language_version: python3
        require_serial: true
        types: [gdscript]
        additional_dependencies: [setuptools]
  - repo: local
    hooks:
      - id: godot-classname-check
        name: Godot class/file naming convention
        entry: ./check_godot_classnames.sh
        language: system
      - id: godot-scene-naming-check
        name: Godot scene naming convention
        entry: ./check_godot_scene_names.sh
        language: system
